services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - 5000:5000
    env_file:
      - .env    
    networks:
      - R6Tracker
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5433:5432
    networks:
      - R6Tracker
    env_file:
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 5558:8080
    networks:
      - R6Tracker
networks:
  R6Tracker:
    driver: bridge
volumes:
  postgres_data:
